import { zos } from './config.js';

// JCL is a fixed 80-column card format. Anything past column 71 is ignored by
// the reader, so job cards are built rather than typed to keep them in range.
export function jobCard(name, options = {}) {
  const {
    account = zos.account,
    programmer = 'K6',
    jobClass = zos.jobClass,
    msgClass = zos.msgClass,
    notify = zos.hlq,
  } = options;

  return `//${name.padEnd(8).slice(0, 8)} JOB (${account}),'${programmer}',CLASS=${jobClass},
//         MSGCLASS=${msgClass},MSGLEVEL=(1,1),NOTIFY=${notify}`;
}

// IEFBR14 does nothing and returns zero. It is the cheapest possible job on the
// system, which makes it the right probe for measuring JES throughput without
// measuring the application under it.
export function nullJob(name = 'K6NULL') {
  return [jobCard(name), '//STEP1    EXEC PGM=IEFBR14', ''].join('\n');
}

// IEBGENER copies SYSUT1 to SYSUT2. With instream input it produces a small,
// predictable amount of spool output for testing spool retrieval.
export function copyJob(name = 'K6COPY', lines = 20) {
  const payload = Array.from(
    { length: lines },
    (_, i) => `RECORD ${String(i + 1).padStart(5, '0')} GENERATED BY K6`,
  );

  return [
    jobCard(name),
    '//STEP1    EXEC PGM=IEBGENER',
    '//SYSPRINT DD SYSOUT=*',
    '//SYSIN    DD DUMMY',
    '//SYSUT2   DD SYSOUT=*',
    '//SYSUT1   DD *',
    ...payload,
    '/*',
    '',
  ].join('\n');
}

// A job that burns CPU for a bounded number of iterations. Useful as a load
// generator when the point of the test is JES and WLM behaviour under queue
// depth rather than the correctness of any one application.
export function sortJob(name = 'K6SORT', records = 5000) {
  const rows = Array.from({ length: Math.min(records, 500) }, (_, i) =>
    `${String((i * 7919) % records).padStart(8, '0')} FILLER`,
  );

  return [
    jobCard(name),
    '//STEP1    EXEC PGM=SORT',
    '//SYSOUT   DD SYSOUT=*',
    '//SORTIN   DD *',
    ...rows,
    '/*',
    '//SORTOUT  DD DUMMY',
    '//SYSIN    DD *',
    '  SORT FIELDS=(1,8,CH,A)',
    '/*',
    '',
  ].join('\n');
}
